#ifndef __PHEROMONESSETTINGS_IN_H_
#define __PHEROMONESSETTINGS_IN_H_
// clang-format off

#define GENERIC_RESPONSE_DETAILS_SIZE (@GENERIC_RESPONSE_DETAILS_SIZE@)

#define FUNCTION_NAME_SIZE (@FUNCTION_NAME_SIZE@)
#define FUNCTION_ARGUMENT_COUNT (@FUNCTION_ARGUMENT_COUNT@)
#define FUNCTION_ARGUMENT_NAME_SIZE (@FUNCTION_ARGUMENT_NAME_SIZE@)

#define BUZZ_PAYLOAD_SIZE (@BUZZ_PAYLOAD_SIZE@)

// clang-format on
#endif // __PHEROMONESSETTINGS_IN_H_
