#ifndef __PHEROMONESSETTINGS_IN_H_
#define __PHEROMONESSETTINGS_IN_H_
// clang-format off

#define GENERIC_RESPONSE_DETAILS_SIZE (@GENERIC_RESPONSE_DETAILS_SIZE@)

#define FUNCTION_NAME_SIZE (@FUNCTION_NAME_SIZE@)
#define FUNCTION_ARGUMENT_COUNT (@FUNCTION_ARGUMENT_COUNT@)
#define FUNCTION_ARGUMENT_NAME_SIZE (@FUNCTION_ARGUMENT_NAME_SIZE@)

#define BUZZ_PAYLOAD_SIZE (@BUZZ_PAYLOAD_SIZE@)
#define BUZZ_MESSAGES_LIST_SIZE (@BUZZ_MESSAGES_LIST_SIZE@)

#define BYTES_PAYLOAD_SIZE (@BYTES_PAYLOAD_SIZE@)
#define NEIGHBORS_LIST_SIZE (@NEIGHBORS_LIST_SIZE@)
#define AGENTS_LIST_SIZE (@AGENTS_LIST_SIZE@)

#define NETWORK_SSID_MAX_LENGTH (@NETWORK_SSID_MAX_LENGTH@)
#define NETWORK_PASSWORD_MAX_LENGTH (@NETWORK_PASSWORD_MAX_LENGTH@)

#define INTERLOC_BEEBOARDS_SIZE (@INTERLOC_BEEBOARDS_SIZE@)
#define INTERLOC_RAW_ANGLE_FRAMES_SIZE (@INTERLOC_RAW_ANGLE_FRAMES_SIZE@)
#define INTERLOC_DUMP_MAX_UPDATES_SIZE (@INTERLOC_DUMP_MAX_UPDATES_SIZE@)

// clang-format on
#endif // __PHEROMONESSETTINGS_IN_H_
