#ifndef __PHEROMONESSETTINGS_IN_H_
#define __PHEROMONESSETTINGS_IN_H_
// clang-format off

#define GENERIC_RESPONSE_DETAILS_SIZE (@GENERIC_RESPONSE_DETAILS_SIZE@)

#define FUNCTION_CALL_NAME_SIZE (@FUNCTION_CALL_NAME_SIZE@)
#define FUNCTION_CALL_ARGUMENT_COUNT (@FUNCTION_CALL_ARGUMENT_COUNT@)

// clang-format on
#endif // __PHEROMONESSETTINGS_IN_H_