set_default(GENERIC_RESPONSE_DETAILS_SIZE 32)

set_default(FUNCTION_NAME_SIZE 32)
set_default(FUNCTION_ARGUMENT_COUNT 8)
set_default(FUNCTION_ARGUMENT_NAME_SIZE 16)

set_default(BUZZ_PAYLOAD_SIZE 16)
set_default(BUZZ_MESSAGES_LIST_SIZE 8)

set_default(BYTES_PAYLOAD_SIZE 200)
set_default(NEIGHBORS_LIST_SIZE 50)
set_default(AGENTS_LIST_SIZE 50)

set_default(NETWORK_SSID_MAX_LENGTH 32) # IEEE max length for SSIDs
set(NETWORK_PASSWORD_MAX_LENGTH 63) # WPA2 password max characters

set_default(INTERLOC_BEEBOARDS_SIZE 3)
set_default(INTERLOC_RAW_ANGLE_FRAMES_SIZE 3)
set_default(INTERLOC_DUMP_MAX_UPDATES_SIZE 20)
set_default(INTERLOC_ANTENNAS_PER_PAIR 2)
set_default(INTERLOC_MAX_ANTENNA_PAIRS 3)
set_default(INTERLOC_MAX_PDOA_SLOPES 2)
