set_default(GENERIC_RESPONSE_DETAILS_SIZE 32)

set_default(FUNCTION_NAME_SIZE 32)
set_default(FUNCTION_ARGUMENT_COUNT 8)
set_default(FUNCTION_ARGUMENT_NAME_SIZE 16)

set_default(BUZZ_PAYLOAD_SIZE 16)

set_default(BYTES_PAYLOAD_SIZE 200)
set_default(NEIGHBORS_LIST_SIZE 50)
